# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W83tzuf2aeAusMJR-tOy4gn7KHhZKVpt
"""

nome = input("")
print("Hello, " + nome, end="")