# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W83tzuf2aeAusMJR-tOy4gn7KHhZKVpt
"""

entrada = input().split(" ")
a = int (entrada [0])
b = int (entrada [1])
c = int (entrada [2])
m1 = (a + b + abs(a - b)) // 2
m2 = (c + m1 + abs(m1 - c)) // 2
print(m2, end="")